### ISSUE TITLE
Unpublished/Deleted nodes are not removed from GraphQL

### ISSUE THREAD

**Issue by IvanShymanovich** [contentstack/gatsby-source-contentstack#10]
Hi,
We have a problem at our project when calling `/__refresh` API from ContentStack, which invokes `sourceNodes` function. If works fine for new content and updated entries, but the plugin doesn't reflect content unpublishing/deletion from ContentStack in GraphQL. As I can see, you have node creation only ([here](https://github.com/contentstack/gatsby-source-contentstack/blob/c776765f0b88a03455a71f9c1776ab80e732c1bf/gatsby-node.js#L49) and [here](https://github.com/contentstack/gatsby-source-contentstack/blob/c776765f0b88a03455a71f9c1776ab80e732c1bf/gatsby-node.js#L55)), but there is no any check for deleted content types and entries, so we always have to restart our preview instance to see changes.
I [see](https://github.com/contentstack/gatsby-source-contentstack/issues/9#issuecomment-509276795) you are working on [Contentstack Sync APIs](https://www.contentstack.com/docs/apis/content-delivery-api/#synchronization). Is it going to fix the issue?

**Comment by harshalpatel91** [comment]
Hi @IvanShymanovich ,

In sync api we would get deleted or unpublish events with it's metadata so we can run deleteNode function so it will remove those nodes. I believe this should resolved bug. I will dig more on /__refresh API to get more insight.

**Comment by IvanShymanovich** [comment]
Basically, `/__refresh` hook simply calls `sourceNodes`, so you'll anyway handle this hook. Since the new API returns content delta, I hope this should not be a problem to handle both published and unpublished contents.
@harshalpatel91 do you have a planned release date or a rough guess?
Thanks!

**Comment by harshalpatel91** [comment]
@IvanShymanovich , 
A rough guess would be by next weekend, we will have a first cut to try out. Will add it in feature branch to try it out.

**Comment by harshalpatel91** [comment]
Hey, @IvanShymanovich

We have added sync API support for source plugin. The first cut of this is present in using-sync-api branch. We have used deleteNode API for deleting the nodes, I believe your bug should get resolve now.  Can you try out this and help with your feedback.

**Comment by IvanShymanovich** [comment]
hey, @harshalpatel91 
Sorry for the late reply, I didn't have a time to verify the new version. I've just done that with `"gatsby-source-contentstack": "2.0.1-rc.0"` and it worked well, nodes where removed. Looking forward for release of `v2`. And, I think, the issue can be closed as soon as the new version is released.
Thanks!

**Comment by harshalpatel91** [comment]
Thanks @IvanShymanovich ,

We have release the RC build, pls update to latest version. Closing this bug
