### ISSUE TITLE
Remove built code from repository

### ISSUE THREAD

**Issue by psykzz** [contentstack/gatsby-source-contentstack#113]
Would we be willing to change the way we build / release this plugin to avoid committing built objects to the repository?
We could avoid this by improving the publish process to include a build step beforehand.

For the build process, I have another issue #114 where i proposed how we could build the project going forward.

If however we don't want to take that approach, we could still remove the built objects and have whatever the current build process is build & include them prior to release.

**Comment by vkalta** [comment]
@psykzz Thanks for the suggestion once again. We will look into this ASAP.

**Comment by abhishek305** [comment]
Closing this as the github action for releasing is in place.
