### ISSUE TITLE
Gatsby 4 support warning

### ISSUE THREAD

**Issue by psykzz** [contentstack/gatsby-source-contentstack#118]
`warn Plugin gatsby-source-contentstack is not compatible with your gatsby version 4.3.0 - It requires gatsby@^3.0.0`

The plugin however does work fine for gatsby 4, outside of #117 (so far).

**Comment by vkalta** [comment]
@psykzz We have released version 4.0.0 with support for gatsby v4. This warning should no longer exist. Please check and confirm. :)

**Comment by psykzz** [comment]
All good! Thanks for version 4! 🥳
