### ISSUE TITLE
sync api - needs better error handling

### ISSUE THREAD

**Issue by andrejpavlovic** [contentstack/gatsby-source-contentstack#12]
There needs to be better error handling here:
https://github.com/contentstack/gatsby-source-contentstack/blob/cb5cabc51644bb9526cea6b1067ebae8520d4bca/src/fetch.js#L75-L77

The `data` object could be an error message like this:
```javascript
{ error_message: 'We can\'t find that Stack. Please try again.',
  error_code: 109,
  errors: { api_key: [ 'is not valid.' ] } }
```

Instead of throwing an error or something similar, I get `TypeError: Cannot read property 'reduce' of undefined` because the code proceeds as if the return was successful.

**Comment by harshalpatel91** [comment]
Valid point @andrejpavlovic , will add an error handling over there.

**Comment by andrejpavlovic** [comment]
Thanks, works better now.
