### ISSUE TITLE
sync api - access_token renamed to delivery_token - please add deprication warning

### ISSUE THREAD

**Issue by andrejpavlovic** [contentstack/gatsby-source-contentstack#13]
I'm not sure why configuration option `access_token` was renamed to `delivery_token`, it breaks compatibility with the master branch. There should at least be an error or deprication warning to tell someone who is trying out this plugin branch, that `access_token` is no longer supported.

**Comment by harshalpatel91** [comment]
@andrejpavlovic - In sync api we require delivery tokens, access_token are not worked over there so we added delivery_token in config. Will add an deprication warning for this.

**Comment by andrejpavlovic** [comment]
Thanks for updating the readme.
