### ISSUE TITLE
Unpublished asset references break gatsby builds

### ISSUE THREAD

**Issue by iyerrama29** [contentstack/gatsby-source-contentstack#140]
**Issue type**: showstopper

**Issue**: Unpublished asset breaks builds

**Issue-root-cause**:
https://github.com/contentstack/gatsby-source-contentstack/blob/00ba5b4001ecde0faee11d025b3397a0ac8ff4b7/src/normalize.js#L130

- `{}` is returned, when the value is `null`
- The GraphQL schema definition expects either a `null` OR an `asset` type
- The buids break since `{}` does not comply with neither of the above types

**Comment by vkalta** [comment]
@iyerrama29 We have released this fix in version 3.1.4. Thanks for your contribution. :)
