### ISSUE TITLE
Can you please bump the Gatsby peer dependency to v4 ?

### ISSUE THREAD

**Issue by jbertel2** [contentstack/gatsby-source-contentstack#145]
https://github.com/contentstack/gatsby-source-contentstack/blob/5c0d5b3687a583f92887633bdc1acb036b1165c8/package.json#L60

It will avoid warnings like this:

`warn Plugin gatsby-source-contentstack is not compatible with your gatsby version 4.10.3 - It requires gatsby@^3.0.0`

**Comment by abhishek305** [comment]
@jbertel2 We have addressed this in the next release of the source plugin which will be out soon.
Thanks for the input.
