### ISSUE TITLE
Getting access denied with stack and delivery token for azure-na-api.contentstack.com

### ISSUE THREAD

**Issue by littlefengers** [contentstack/gatsby-source-contentstack#147]
Hello,

I'm trying to connect to our stack with the plugin, but getting "Cannot access Contentstack with ...." error

The host address is: azure-na-api.contentstack.com, I've tried using that for the CDN property in the gatsby config, but still getting same error.

Is #143 supposed to fix that issue? When will there be a release?

**Comment by abhishek305** [comment]
Hi @littlefengers,
I tried to reproduce it on my end & it's working fine.
Could you share your **gatsby-config.js**?

In the **gatsby config.js**, we have an option for cdn URL below is an example:
Could you please try the below example

``` javascript
{
     resolve: "gatsby-source-contentstack",
     options: {
        api_key: CONTENTSTACK_API_KEY,
        delivery_token: CONTENTSTACK_DELIVERY_TOKEN,
        environment: CONTENTSTACK_ENVIRONMENT,
        cdn: `https://azure-na-cdn.contentstack.com/v3`,
        expediteBuild: true,
        enableSchemaGeneration: true,
        type_prefix: "Contentstack", // (default),
        downloadImages: false,
        locales: ["en-us"],
}
```

This [#143](https://github.com/contentstack/gatsby-source-contentstack/pull/143) will be released soon and is not related to the issue you are facing.

Thanks
Abhishek
