### ISSUE TITLE
This plugin does not support reference value with multiple types

### ISSUE THREAD

**Issue by teavirdis** [contentstack/gatsby-source-contentstack#15]
` ERROR #11321  PLUGIN

"gatsby-source-contentstack" threw an error while running the sourceNodes lifecycle:

Cannot read property 'filter' of undefined

  TypeError: Cannot read property 'filter' of undefined
  
  - normalize.js:114 
    [content-pages]/[gatsby-source-contentstack]/normalize.js:114:43
  
  - Array.forEach`

after https://www.contentstack.com/docs/guide/content-types/reference-field-upgradation

**Comment by harshalpatel91** [comment]
Hey @teavirdis ,

We have a [RC candidate](https://github.com/contentstack/gatsby-source-contentstack/tree/2.0.0-rc.0) which we have push, we will be pushing this live very soon till then you can try the RC build. Try your various cases for this reference field and do let us know if you found any issues or any recommendation for this. 

Regards,

**Comment by harshalpatel91** [comment]
Hey @teavirdis,

We have release this RC pls update to latest version. Closing this bug.
