### ISSUE TITLE
"The gatsby-source-contentstack plugin has generated no Gatsby nodes"

### ISSUE THREAD

**Issue by littlefengers** [contentstack/gatsby-source-contentstack#150]
I'm getting "The gatsby-source-contentstack plugin has generated no Gatsby nodes. Do you need it? This could also suggest the
plugin is misconfigured." 

There are no errors connecting to the stack (cdn: https://azure-na-cdn.contentstack.com/v3) using the plugin, but nothing is showing in the graphql explorer. 

I can use fetch and it is returning the correct data.

**Comment by abhishek305** [comment]
Hi @littlefengers,

Thanks for raising your concern, would you please share/explain more about what you are trying to achieve & details regarding how you are setting up the following things:

- gatsby config
- error message
- source plugin version & gatsby version 
- Graphql explorer screenshot (if possible)

**Comment by littlefengers** [comment]
Hey, if you have access, there's a support ticket: #00020186

**Comment by visualjeff** [comment]
Still broken.  Plug fails but the same request using cURL works perfectly fine.

```
https://azure-na-cdn.contentstack.com/v3/content_types?environment=development&include_count=true&include_global_field_schema=true&limit=100&skip=0
{
  "headers": {
    "X-User-Agent": "contentstack-gatsby-source-plugin-4.0.3",
    "api_key": "XXXXXXXXXXXXXX",
    "access_token": "XXXXXXXXXXXXXXXXXXX"
  }
}

Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: Gunzip {
      _writeState: [Uint32Array],
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      bytesWritten: 0,
      _handle: [Zlib],
      _outBuffer: <Buffer 00 00 00 00 00 00 00 00 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 16334 more bytes>,
      _outOffset: 0,
      _chunkSize: 16384,
      _defaultFlushFlag: 2,
      _finishFlushFlag: 2,
      _defaultFullFlushFlag: 3,
      _info: undefined,
      _maxOutputLength: 4294967296,
      _level: -1,
      _strategy: 0,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null,
      [Symbol(kError)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://azure-na-cdn.contentstack.com/v3/content_types?environment=development&include_count=true&include_global_field_schema=true&limit=100&skip=0',
    status: 200,
    statusText: 'OK',
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
}

// Returned payload
{
  "content_types": [],
  "count": 0
}

```

**Comment by visualjeff** [comment]
Ive made some progress.  I'm able to load content types but not able to pull any data.

```
https://azure-na-cdn.contentstack.com/v3/stacks/sync?environment=development&include_count=true&sync_token=XXXXXXXXXXXXXXXXXX
{
  "items": [],
  "skip": 0,
  "limit": 100,
  "total_count": 0,
  "sync_token": "XXXXXXXXXXXXXXXXXX"
}
```

**Comment by abhishek305** [comment]
Hi @visualjeff @littlefengers,

Sorry for the inconvenience. 

The team is checking this internally as this is an issue with Content Delivery API and not from the source plugin.
As gatsby source plugin is dependent on CDA services to fetch the data & create appropriate nodes which is why this issue surfaced.

Someone from the CSE team will get back to you with the registered support ticket: #00020186 and rectify this issue.

Thanks !!
Abhishek

cc @surajcontentstack

**Comment by visualjeff** [comment]
ContentStack has acknowledged the issue and hopes to have it resolved soon.

**Comment by abhishek305** [comment]
Hi @visualjeff @littlefengers,

The Team has resolved the issue from CDA's end and I have verified the data getting pulled in via the source plugin.

Thanks !!

**Comment by visualjeff** [comment]
Confirmed.

Thank you.
