### ISSUE TITLE
Assets fetch from all locales on build

### ISSUE THREAD

**Issue by samaritanau** [contentstack/gatsby-source-contentstack#179]
Hi,

We are setting the locales in the gatsby-source-contentstack options to "en-au" however all assets from all locales are being downloaded at build time.

Any way to stop that?

Regards,
Henry

**Comment by abhishek305** [comment]
Hi @samaritanau,
Could you possibly share the gatsby-config for source contentstack?
Just needed to know how you are using the `locale` config option.
here is an example :   `locales: [‘en-au']`

**Comment by samaritanau** [comment]
Hi Abhishek,

Config block below, worth mentioning that it's only the assets that it's pulling all in, not the entry's, they are working as expected.

` `gatsby-plugin-gatsby-cloud`,
    {
      resolve: `gatsby-source-contentstack`,
      options: {
        api_key: process.env.CS_API_KEY,
        delivery_token: process.env.CS_DELIVERY_TOKEN,
        environment: process.env.CS_ENV,
        expediteBuild: process.env.NODE_ENV === "production",
        enableSchemaGeneration: true,
        locales: [`${process.env.GATSBY_SITE_LOCALE || "en-au"}`],
      },
    },`

In the .env.development file:

GATSBY_SITE_LOCALE='en-au'

**Comment by abhishek305** [comment]
Hi @samaritanau ,

Thanks for sharing the config, as I can see from the config you are not using the config option 
`downloadImages: boolean_value,` assuming you are not downloading assets locally.

If you are using the `downloadImages: boolean_value,` with `true` it would download all the assets locally as the image delivery API we are using in our source plugin to download assets locally does not support locale. Generally, assets in Contentstack are not associated with locales it's only when an asset is being used in an entry or corresponding entry locale. 

The config option `locales:['en-us']` would only work for entries.
Hope this helps, let me know if you have questions.

**Comment by InterestingDeploys** [comment]
ok, thanks then.

**Comment by samaritanau** [comment]
ok, thanks then @abhishek305
