### ISSUE TITLE
V5 readiness

### ISSUE THREAD

**Issue by teavirdis** [contentstack/gatsby-source-contentstack#188]
Hi, could you please share some plans regarding https://github.com/contentstack/gatsby-source-contentstack/tree/feat/plugin-v5-updates
How stable is it? Do you have any plans about release?
Thank you in advance!

**Comment by abhishek305** [comment]
Hi @teavirdis 

We have already published v5.0.0 of gatsby-source-contentstack
Please check here: https://www.npmjs.com/package/gatsby-source-contentstack
Also, refer to the notes in README for prerequisites. and the gatsby migration guide [here](https://v5.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/)

Thanks !!

**Comment by teavirdis** [comment]
Thank you for the great news!
