### ISSUE TITLE
Image asset - width and height not available

### ISSUE THREAD

**Issue by andrejpavlovic** [contentstack/gatsby-source-contentstack#19]
There is no width and height available for images. Is there a way to add that to graphql without having to download all the images and manually check the size?

**Comment by harshalpatel91** [comment]
Hi @andrejpavlovic,

Currently, I believe their is no way to add width & height without downloading in source plugin. But I will connect with gatsby team for this if they have provision to add this in source plugin. Till then you can add directly append image url in JSX.

Thanks

**Comment by andrejpavlovic** [comment]
I did some more digging around, and it looks like it is possible to get the dimensions from the [assets api endpoint](https://www.contentstack.com/docs/apis/content-delivery-api/#get-a-single-asset) without downloading the image. Is this data not included in the sync API?

**Comment by harshalpatel91** [comment]
Hi @andrejpavlovic ,

Let me connect with the api team for this and will see if we can add this in query params of Sync API

**Comment by andrejpavlovic** [comment]
Any news on this?

**Comment by harshalpatel91** [comment]
Hi @andrejpavlovic,

Currently, It's not suppport in sync api.

I have raised the enhancement for this on sync api call. It will be added in Sync api. Will update you here once we get ETA for this. Thanks!

**Comment by andrejpavlovic** [comment]
Hey @harshalpatel91, any ETA updates on this?

**Comment by harshalpatel91** [comment]
Hey @andrejpavlovic,

I will follow up with the team to get the ETA.

**Comment by andrejpavlovic** [comment]
So we've added logic to fetch the dimension info whenever a new asset entry is synced into gatsby by making a request to the single asset api endpoint, but it's relatively slow and often triggers timeouts if a large number of assets is being synced at once across the 20 locales that we support. Any progress with your team on this?

**Comment by harshalpatel91** [comment]
Hi @andrejpavlovic,

I had a discussion with the API team and we are convinced that this support should be provided as soon as possible in Sync API. We will have an ETA very soon on this.

**Comment by ninadhatkar** [comment]
Hello @andrejpavlovic ,

Sorry to keep this in waiting for a long.

The API team has resolved this. You should now get the height width parameter in objects. 

Please verify and let us know.

**Comment by vkalta** [comment]
As there is no response from the user, we can consider this as resolved.

**Comment by szimek** [comment]
Hi! Has it been actually implemented and released?

I've got a content type with modular blocks and one of these blocks is a block with a file field (with "Allow images only" option set). However, in Gatsby (3.x, haven't checked it in 2.x yet) I'm getting only image title and url.

Should it just work, or is there some option I need to enable?
