### ISSUE TITLE
Reference field - always returns array

### ISSUE THREAD

**Issue by MarcoDaniels** [contentstack/gatsby-source-contentstack#20]
If we define a reference field as **not** multiple it always returns an array. 

Shouldn't it check if the field is multiple and return object instead?

**Comment by harshalpatel91** [comment]
Hi @MarcoDaniels,

From API reference field always returns in array only, irrespective of single or multiple.

**Comment by harshalpatel91** [comment]
Hey @MarcoDaniels, 

Closing the Issue, reopen if you have any other question or issue releated to reference field.
