### ISSUE TITLE
Markdown field to HTML

### ISSUE THREAD

**Issue by MarcoDaniels** [contentstack/gatsby-source-contentstack#22]
Would it be possible to expand the markdown field from contentstack and get the data as HTML?

**Comment by harshalpatel91** [comment]
Thanks @MarcoDaniels, 

For bringing this request, we will evaluate this...  It will be an interesting functionality to transfer markdown field to HTML while resolving the node for gatsby.

**Comment by MarcoDaniels** [comment]
Hey @harshalpatel91, I opened a pull request with the code to transform markdown to html here: https://github.com/contentstack/gatsby-source-contentstack/pull/23

**Comment by harshalpatel91** [comment]
Hi @MarcoDaniels,

I will put forward this changes to the whole team, since their will be a breaking change for markdown field response.

**Comment by MarcoDaniels** [comment]
> Hi @MarcoDaniels,
> 
> I will put forward this changes to the whole team, since their will be a breaking change for markdown field response.

I'm thinking that we could also create a new field if it is markdown and transform that new field into HTML and keep the original field as markdown, that way it would not have any breaking changes.

**Comment by harshalpatel91** [comment]
Hi @MarcoDaniels,

let me connect with the whole team on this and will update you here.

**Comment by Steveeeie** [comment]
We require markdown raw, so please support both if this is required

**Comment by harshalpatel91** [comment]
Hi @Steveeeie ,

Yes, we would not break the existing response will try to add a new field for markdown transformation if required. 

Thanks

**Comment by MarcoDaniels** [comment]
I'm going to close the issue and PR as we will not longer need the transformation in the plugin. It will happen in the client instead.
