### ISSUE TITLE
Increase speed of fetching step

### ISSUE THREAD

**Issue by szimek** [contentstack/gatsby-source-contentstack#24]
Hi! We've got ~5000 entries and ~13000 assets in one stack at the moment and fetching all this data takes a while... It looks like the requests to sync all this data are paginated and done sequentially. 

Is it possible to increase the `limit` option e.g. from 100 to 1000? I couldn't find in the documentation what the maximum value for `limit` option is.

Or maybe it it would be possible to make these requests in parallel e.g. in 5 or so?

**Comment by harshalpatel91** [comment]
Hi @szimek,

Let me check with the API team for increasing the limit and also we can consider the parallel request in sync by type. Will connect with team for this and will get back to you.

**Comment by szimek** [comment]
@harshalpatel91 Hi! Any updates on this?

**Comment by harshalpatel91** [comment]
Hi @szimek,

We have checked from API team, but currently we don't have any way to increase the limit. So will have to evaluate other ways to handle this by parallel request.

**Comment by szimek** [comment]
Hi! Any updates on this?

As we add more content to our stack, it takes now even longer to fetch it all.

Fetching step takes ~13 minutes when I run `gatsby build` command locally on my laptop:
```
Starting to fetch data from Contentstack
Fetch Contentstack data: 754942.706ms
```
and ~8 minutes on our Jenkins (AWS):
```
Starting to fetch data from Contentstack
Fetch Contentstack data: 460034.282ms
```

**Comment by asmit-patil** [comment]
Hi @szimek ,

we have fixed this by syncing the assets, entries and content types parallelly while the build process in the v2.1.0. Refer the [config options](https://github.com/contentstack/gatsby-source-contentstack#how-to-use). You have to set the expediteBuild to true while running the gatsby build command. 

Please use this and let us know with your feedback.

Thanks.

**Comment by szimek** [comment]
Hi @asmit-patil !

The builds got faster now, e.g. on my laptop the fetching step takes now about 7 minutes, compared to 13 minutes I mentioned before. It's still rather slow though, especially when developing the app, as Gatsby will often remove the cache, e.g. when updating its configuration.

We've just enabled Gatsby Preview (free plan for now just to try it out) in our Contentstack and after publishing a single page it takes 2-3 minutes to rebuild it, which is still longer than I hoped for, but much better than 15 minutes it takes our Jenkins to build and deploy it.

I was wondering if you know of any build performance improvements we could still make. E.g., we have a lot of content types in our stack, but only a handful of them are used in our Gatsby app - do you think that if there was a way to tell Gatsby to skip generating schema and nodes for the content types not used by the app, it somehow would speed up the `develop` & `build` tasks?

Also, somewhat unrelated issue is that even when we publish to all languages at once, Contentstack will still trigger a webhook for each language separately. The first preview build in Gatsby Preview takes about 2-3 minutes and creates pages for all languages already. The next ones triggered for the other languages take ~10s, because nothing has changed, so these builds are unnecessary.

**Comment by vkalta** [comment]
This has been resolved.
