### ISSUE TITLE
Mark GraphQL field as NonNullable when is Mandatory in Contentstack

### ISSUE THREAD

**Issue by MarcoDaniels** [contentstack/gatsby-source-contentstack#25]
Having the GraphQL field as non null when the field is marked as mandatory in contentstack would be a great help when using Typescript.

**Comment by harshalpatel91** [comment]
Hi @MarcoDaniels ,

I'm tagging this in our enhancement request. Thanks for bringing this up

**Comment by andrejpavlovic** [comment]
This is really a dupe of #26

**Comment by asmit-patil** [comment]
Hi  @andrejpavlovic @MarcoDaniels ,
We have fixed this issue in version [2.2.0](https://github.com/contentstack/gatsby-source-contentstack/tree/2.2.0)

Closing the Issue, reopen if you have any other question or issue releated to reference field.
