### ISSUE TITLE
Use the ability to customize the graphQL schema

### ISSUE THREAD

**Issue by stefanhar** [contentstack/gatsby-source-contentstack#26]
We are having problems with fields not being defined when newly created and nested data structures seem to become undefined when empty.
This is propaply due to gatsby inferring the GraphQL schema.

It would be optimal if the plugin generated schema via the [custom schema generation](https://www.gatsbyjs.org/docs/schema-generation/) in gatsby.
Inserting exported content types into the plugin could also be an option. Prismics allows this with the [schema option.](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/README.md#providing-json-schemas)

This would ensure fields exist and are of the correct type even if they are newly created and have never had any content.
This would also ensure nested data structures are defined.

**Comment by harshalpatel91** [comment]
Hi @stefanhar,

Thanks for your suggestion. This is really helpful. 

In our current implementation, the schema is generated by Gatsby, so the structure might have empty nested objects. Adding schema based on content types would be a great way to handle this. Thanks again for suggesting this. We will certainly consider implementing this. 

I really like your approach and appreciate you bringing this up. Request you to please keep suggesting such ideas, which will eventually increase the usability of this plugin. 

Regards,
Harshal

**Comment by jdesherlia** [comment]
We have this exact same issue, and it is currently causing us an immense amount of problems. Any content type that is a single entry type cannot have optional fields, and any content type that has a field group has to have data in that group in all entries, otherwise Gatsby detects a type mismatch and prunes the data from the GraphQL schema.

**Comment by andrejpavlovic** [comment]
We've actually hook into the createSchemaCustomization API and generate the full GraphQL schema directly from the conten_types and global_fields export. It definitely required a decent chunk of effort and that's for just a barebones untested solution. It was the only way we could get reliable strong typing to work with Typescript.

**Comment by harshalpatel91** [comment]
Hi @andrejpavlovic,

I would love to see your solution on createSchemaCustomization API, We are also trying to use the same to give the full GraphQL schema on content-types. Any fork branch where we can see your implementation.

Thanks!

**Comment by jdesherlia** [comment]
@harshalpatel91 one thing I have been wondering about is how you are going to build this to also support custom extensions. We have a pretty heavy reliance on custom extensions that store data as json, for every content type. ContentStack doesn't know what the underlying structure of those is beyond being json objects.

The way I see it, you would either need to give us some way to provide that intended schema to you, via gatsby-config plugin settings , or skip those and let Gatsby infer type for those unknowns. If you let it infer types, that should be documented clearly so anyone creating custom extensions knows that their underlying data needs to be the same shape in all circumstances.

@andrejpavlovic did you encounter this in your implementation?

**Comment by harshalpatel91** [comment]
Yes, @jdesherlia for custom fields will try to skip and will let Gatsby infer those types for unknowns schema.  We can also evaluate of giving a way to provide the intended schema for the custom fields.

**Comment by jbertel2** [comment]
+ 1 for this request to generate GraphQl schema from content types

**Comment by jdesherlia** [comment]
@harshalpatel91 any update on this? We are keen to test out a proposed solution. I think it would be a huge difference maker for ContentStack + Gatsby.

**Comment by ninadhatkar** [comment]
Hi @jdesherlia ,

We are in the process of adding this to the plugin. Please refer the PR here:
https://github.com/contentstack/gatsby-source-contentstack/pull/30

@jacobimpson @jbertel2 @andrejpavlovic @stefanhar 
If possible can you guys have look at it and provide feedback will be helpful. We have added one config key which allows you to switch between previous behavior and custom schema defination by content type.

Here is the branch link: https://github.com/contentstack/gatsby-source-contentstack/tree/customSchema 

Thanks,

**Comment by ninadhatkar** [comment]
Thanks @stefanhar, for reviewing the PR and having valuable feedback. 

We will be merging this PR by EOD today. If anyone still has any feedback regarding https://github.com/contentstack/gatsby-source-contentstack/pull/30 PR please share with us.

**Comment by asmit-patil** [comment]
Hi @jacobimpson @jbertel2 @andrejpavlovic @stefanhar,
We have fixed this issue in version [2.2.0](https://github.com/contentstack/gatsby-source-contentstack/tree/2.2.0)

Closing the Issue, reopen if you have any other question or issue releated to reference field.
