### ISSUE TITLE
Improve Gatsby Preview support by allowing to pull unpublished latest versions

### ISSUE THREAD

**Issue by jbertel2** [contentstack/gatsby-source-contentstack#28]
Currently, Gatsby Preview can only preview content that is published, because this Gatsby plugin uses the delivery token to fetch entries from the delivery API. This typically results in the addition of a specific 'preview' environment in ContentStack to allow previews before publishing to a higher environment. 

I believe it would be a better user experience for content editors, if they could preview the latest version, regardless of the publication status. The Delivery API support this through an access token (not via delivery tokens), but this plugin only allows delivery tokens atm.

**Comment by harshalpatel91** [comment]
Hi @jbertel2 ,

In our current implementation, we are using sync api to fetch the published data which uses delivery tokens. In sync api we don't get draft data and fetching those through delivery API would be slow as compare to sync one. For now like you mentioned we can do this by 'preview' kind of env. Will still look if this can be supported in sync api to get latest data.

Request you to please keep suggesting such ideas, which will eventually increase the usability of this plugin. 

Thanks!
