### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by benjaminhoffman** [contentstack/gatsby-source-contentstack#4]
Want to decrease the size of this library?  Try:

I think you only use `_.filter` right?  If so, try replacing lodash with: https://www.npmjs.com/package/lodash.filter

Or even better, ditch lodash altogether and use native JS filter method instead.

**Comment by hiteshbal91** [comment]
Yes @benjaminhoffman, Good suggestion. We will decrease the size of the library. 👍

**Comment by hiteshbal91** [comment]
Hi @benjaminhoffman We have removed lodash library from dependency in version 1.0.2.

**Comment by benjaminhoffman** [comment]
nice thx.  unrelated but much higher priority is this bug... can you help nudge the folks there to get this fixed: https://github.com/contentstack/contentstack-javascript/issues/11
