### ISSUE TITLE
Reference field returns incorrect null value in grapql query

### ISSUE THREAD

**Issue by jbertel2** [contentstack/gatsby-source-contentstack#41]
Using v.2.2.5, when i enable schema generation, 1 of our reference fields (named "related_to") on a certain entry has a null value, despite the same entry having a value when fetched through the delivery API.

delivery API response: 
```
"related_to": [
   {
      "uid": "bltceff6f08131e6e3d",
      "_content_type_uid": "specialty"
   }
],
```

graphql query:
```
related_to {
    ... on Contentstack_product {
      title
   }
   ... on Contentstack_specialty {
      title
   }
}
```
graphql query response:
`"related_to": null`

Things i have tried: 
- disable schema generation: the graphql query (slightly adapted) works fine and returns the proper value. This rules out any faults with publishing the entry or the referred entry.

**Comment by ninadhatkar** [comment]
Hi @jbertel2 

We are looking into it. Will keep you posted.


Thanks,
Ninad Hatkar

**Comment by jbertel2** [comment]
I have tested the v2.2.6 release which is addressing this issue. It solves the reported issue IF there are entries that refer to all types of the union. 

It introduces new issues in the case where there is no content entry that holds values for all types of the union.
e.g. if the reference field can refer to 3 types, but the content entries only ever refer to 1 of those types, then the graphql type will not be a union and graphql queries such as in the original post will fail:

> Fragment cannot be spread here as objects of type "Contentstack_specialty" can never be of type "Contentstack_product".

**Comment by jbertel2** [comment]
I can confirm that #45 resolved all these issues.
