### ISSUE TITLE
Allow to specify content types and locales to sync

### ISSUE THREAD

**Issue by szimek** [contentstack/gatsby-source-contentstack#47]
Hi!

We've got many content types in our stack, but we use just a few of them in our Gatsby app. It would be great if it was possible to specify which content types should be synced to avoid downloading unnecessary content and created GraphQL schema and nodes for those as well. I understand that this might be not trivial to implement, as Sync API doesn't allow to pass multiple content types, so one would need to track one sync token per content type. 

Maybe Sync API could be adjusted to allow multiple content types? :)

**Comment by szimek** [comment]
Hi!

If we'd come up with a PR that implements this feature by using multiple sync calls (1 per content type/language), would you be willing to merge it?

The development experience in our case is really bad right now, as it takes ~15 minutes (depends on the laptop) to run `yarn develop` and when one is working on updating the content structure or a new Gatsby plugin, Gatsby deletes the cache after every change...

**Comment by imkhan** [comment]
@szimek , thanks for suggesting this enhancement.
We'd definitely review and merge if you send proposed changes in a PR.

**Comment by vkalta** [comment]
@szimek We have added support to specify content-types and locales to sync data. Thanks again for the suggestion.

Cheers!

**Comment by szimek** [comment]
@vkalta Thank you so much!
