### ISSUE TITLE
When i configure multiple stacks  i get this error.

### ISSUE THREAD

**Issue by niranjanbala** [contentstack/gatsby-source-contentstack#56]
ERROR #11321  PLUGIN

"gatsby-source-contentstack" threw an error while running the sourceNodes lifecycle:

Cannot read property 'schema' of undefined

**Comment by ninadhatkar** [comment]
@niranjanbala Thanks for reporting this issue. We are able to reproduce and found the cause of it. We are working on getting this resolved, will keep you posted.

**Comment by vkalta** [comment]
@niranjanbala closing this issue, as this scenario has been handled in the latest patch release.

Cheers!
