### ISSUE TITLE
Support for gatsby-plugin-sharp coming soon?

### ISSUE THREAD

**Issue by jbertel2** [contentstack/gatsby-source-contentstack#58]
Readme.md has had the notice that this support is coming soon for quite a while. Is there any news on that front?

**Comment by vkalta** [comment]
@jbertel2 Yes, we are working on it. We will keep you updated.

**Comment by visualjeff** [comment]
Any updates?

**Comment by cs-ecosystem-dev** [comment]
@visualjeff We are currently working on the branch https://github.com/contentstack/gatsby-source-contentstack/tree/download-assets. It's in QA. We will keep you updated.

**Comment by vkalta** [comment]
@visualjeff We are currently working on the branch https://github.com/contentstack/gatsby-source-contentstack/tree/download-assets. It's in QA. We will keep you updated.

**Comment by vkalta** [comment]
@jbertel2 @visualjeff We have added support for this. The changes are available in the version 2.3.0.
