### ISSUE TITLE
downloadImages config option in v2.3.0 doesn't support the EU tenant

### ISSUE THREAD

**Issue by jbertel2** [contentstack/gatsby-source-contentstack#78]
The image regexp used in v2.3.0 is 'https://(stag-images|images).contentstack.io/v3/assets/'.

Contentstack EU tenant serves images on e.g. https://eu-images.contentstack.com/v3/assets/blt300490332287c269/blt452c4a196e11d1fc/5f6374142d33bb3d0daeed03/regidter.jpeg

**Comment by vkalta** [comment]
@jbertel2 Thanks for raising the issue. We will look into it and push a fix as soon as possible.

**Comment by vkalta** [comment]
@jbertel2 The changes mentioned here has been updated on npm. The changes will be available from version 2.3.1. Thanks for your contribution.
