### ISSUE TITLE
Gatsby 3 support

### ISSUE THREAD

**Issue by lucascaro** [contentstack/gatsby-source-contentstack#89]
[Gatsby 3 is out](https://www.gatsbyjs.com/blog/gatsby-v3/)!

Migration guide:
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

**Comment by ninadhatkar** [comment]
@lucascaro thanks for notifying this. We have added this to our backlog we will keep you posted on further updates.

**Comment by lucascaro** [comment]
Thank you! It might be as easy as releasing a version which has gatsby 3 as a dependency:
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers

**Comment by passion4code** [comment]
@ninadhatkar where does this stand in the backlog? Did you need some community support in testing that it works in both 2 and 3 without additional changes?

**Comment by lucascaro** [comment]
A problem I have found so far:
```
warn Calling "touchNode" with an object containing the nodeId is deprecated. Please pass the node directly to the function: touchNode(node) "touchNode" was called by gatsby-source-contentstack
```

looks like this plugin is using a deprecated invocation of `touchNode` with an ID instead of a node

**Comment by ninadhatkar** [comment]
@passion4code this is still not scheduled yet. We are currently working on some other backlog items. 

It will be helpful if we get community support as well for testing this will cover more scenarios.

@lucascaro thanks for getting this to attention.

Will keep you posted on further updates here.

**Comment by szimek** [comment]
Had anyone else encounter the following error when upgrading to Gatsby 3: `
Error in "/...blog/node_modules/gatsby-source-contentstack/gatsby-node.js": Cannot find module 'babel-runtime/helpers/defineProperty'`
?

Gatsby 3 switched to Babel 7 and Node.js 12+, while this plugin still uses Babel 6 and targets Node.js 4.0+.
