### ISSUE TITLE
Issue with stale fetching of locales

### ISSUE THREAD

**Issue by andrejpavlovic** [contentstack/gatsby-source-contentstack#9]
After trying to figure out why newly added locales were not showing up in gatsby's graphql and talking with support, we narrowed it down to the endpoint `https://cdn.contentstack.io/v3` being used by this plugin. This endpoint should be updated to `https://api.contentstack.io/v3` by default, since for some reason (beyond my understanding) the  `https://cdn...` doesn't update when locales are modified.

Relevant line in code:
https://github.com/contentstack/gatsby-source-contentstack/blob/929a51ba9d680afabfebe11c4ba18c78a8f17d40/src/fetch.js#L10

**Comment by harshalpatel91** [comment]
Hi, @andrejpavlovic 

Thanks for the detailed description. This is a bug.

We are working on using Contentstack [Sync APIs](https://www.contentstack.com/docs/apis/content-delivery-api/#synchronization) in the source plugin which will resolve this issue. This release will also include performance improvements in the build time. We are very close to this release, we’ll keep you posted.

**Comment by harshalpatel91** [comment]
Hey, @andrejpavlovic

We have added sync API support for source plugin. The first cut of this is present in using-sync-api branch. I believe your bug should get resolved now. Can you try this out and help with your feedback.

**Comment by andrejpavlovic** [comment]
Looks like the using-sync-api branch is working well.
