### ISSUE TITLE
I dea: More persistent cache for content

### ISSUE THREAD

**Issue by lucascaro** [contentstack/gatsby-source-contentstack#92]
Hi there, 
While working with this plugin, the gatsby cache gets cleared regularly, especially on development but some times on production as well.

A good example is on development, while changing or adding unrelated plugins, gatsby will clear the cache, and for relatively big stacks, syncing from scratch might take > 15 minutes.

While cache clears are usually needed for different reasons, this is not really the case for this plugin since the sync API can be persisted in an almost completely safe way.

I've had the idea of somehow bypassing gatsby cache clears for this plugin, one option would be adding a setting to do so, and another option would be via a separate plugin that can be used to do it in a generic way.

I'd love to get some feedback on the idea, the feasibility of it (i.e. would everything work well if we had a more persistent cache), as well as where to implement it (is this plugin the right place for it, or is a separate. plugin a better place for it?)

Any thoughts?

**Comment by lucascaro** [comment]
example: https://github.com/lucascaro/gatsby-plugin-persist-cache

**Comment by ninadhatkar** [comment]
Hi, @lucascaro Thanks for the suggestion and for sharing the idea here. We will review this internally and get back to you.

**Comment by vkalta** [comment]
@lucascaro I think this plugin can be used as an independent plugin as it is focussed on gatsby's caching related issue. Thanks for your suggestion.

**Comment by lucascaro** [comment]
@vkalta sadly since this plugin uses the redux store directly a plugin like my example can't really intercept and fix this issue, the gatsby-source-contentstack plugin would need to allow for such measures by maintaining some sort of cache in the filesystem under .cache in order for other plugins to be able to help I think.

**Comment by vkalta** [comment]
@lucascaro Thanks for the suggestion. We will discuss this internally and revert.
