### ISSUE TITLE
Issue load plugin

### ISSUE THREAD

**Issue by faisalike** [contentstack/gatsby-source-contentstack#94]
i have installed a new app for gatsby and add **gatsby-source-contentstack** after adding this i have added my api key and token.

` plugins: [
    {
      resolve: "gatsby-source-contentstack",
      options: {
        api_key: "my api key",
        delivery_token: "my token",
        environment: "development",
      },
    },
  ]`

but after that when i run "npm run develop" i face this error.

![Screenshot 2021-05-20 11 30 34](https://user-images.githubusercontent.com/42367705/118930296-ff867b80-b95e-11eb-8646-0258fa56c761.png)

please suggest me what i missing or something wrong.

**Comment by ninadhatkar** [comment]
@faisalike can try again by reinstalling node modules and cleaning the Gatsby cache?

**Comment by faisalike** [comment]
yes i did try from scratch and worked well.
thanks!
