### ISSUE TITLE
With enableSchemaGeneration option enabled unlocalized entries cause null errors for mandatory fields

### ISSUE THREAD

**Issue by szimek** [contentstack/gatsby-source-contentstack#96]
I'm looking for ways to optimize our build times (`gatsby develop` takes ~10 minutes...) and wanted to try `enableSchemaGeneration` option.

However, I'm getting the following errors:
```
Cannot return null for non-nullable field Contentstack_post.description.
```

After some investigation, I found out that someone published a few articles in a language that is not supported (used) by our Gatsby app, but is available in our stack. This entries were *not* localized, only published, probably for testing purposes.

Even though these entries are not used in the app, they cause this error I mentioned above. If I unpublish them, the error goes away. The issue is that it makes our builds very fragile - if anyone publishes an unlocalized post in any language, it will break the build.

I don't know why unlocalized entries return null value, rather than the value from the fallback language. Is it a bug, or is it an expected behavior?

**Comment by vkaltae9** [comment]
Hi @szimek, sorry for the inconvenience caused. In order to reproduce this issue at my end I would like to know few details like api key and environment details of the stack which is causing this. You can mail them to me @ vikram.kalta@contentstack.com.
Cheers!

**Comment by vkalta** [comment]
Hi @szimek, sorry for the inconvenience caused. In order to reproduce this issue at my end I would like to know few details like api key and environment details of the stack which is causing this. You can mail them to me @ vikram.kalta@contentstack.com.
Cheers!

**Comment by jbertel2** [comment]
@szimek  I have encountered similar issues in the past, which is why i partly decided to contribute the disableMandatoryFields option: https://github.com/contentstack/gatsby-source-contentstack/pull/86 

It is quite drastic as it will make all mandatory fields in the CMS optional in the graphQl schema.
